### PR TITLE
Merge v2 (unstable) into master [incomplete]

### PR DESCRIPTION
**Pull request by mildsunrise**
## Intro / Presentation

After hours, **days**, **WEEKS**, **M O N T H S** of work (yeah, I'm exagerating a bit),
the new, **flaming**, **FASTER** version 2 of Robotskirt is now stable,
and soon it'll be finished and ready to push to [NPM](http://npmjs.org).

As [GitHub itself does](https://github.com/blog/1124-how-we-use-pull-requests-to-build-github), I'm opening this pull request earlier.
Feel free to **post any suggestions or feedback** about the new version here!
Watch this pull request to stay updated on the v2 status and new features.
When we're ready to go, it'll be finally merged and published.

_What_ is still left to do, you ask?
## What is still left to do (and differences over v0-1)

Done  **Update to the latest Sundown** (at the time of writing, it is vmg/sundown@b6b58da3ff)

Done  **Consistent, structured, [faster](#performance) API** with **reusable PARSERS** in addition to renderers.

Done  Update the **README**, benchmark results (see [below](#performance)) and `package.json`.

Done  **Custom renderers!**

Done  **Add a convenience, faster method** to build a standard Renderer/Parser pair in-one-step.

Done  **Switch to Node-GYP** (to support latest versions also)

In progress  **Document the API** and **write some samples**

Done  **Expose [SmartyPants](http://daringfireball.net/projects/smartypants) and [Houdini](https://github.com/vmg/houdini)** (which are bundled with Sundown and Redcarpet).

In progress  **Expose [Autolink](http://daringfireball.net/projects/smartypants)** (Sundown's implementation).

Pending  **Expose the other Sundown renderers**

Pending  **Use [Travis.ci](http://travis-ci.org)** to test & benchmark.

Done  **Write a [manual page](https://github.com/benmills/robotskirt/blob/unstable/man/robotskirt.1)!** See [the screenshot](http://i.imgur.com/du02L.png).

In addition to that, the utilities I wrote for Robotskirt are now
an independent project called [V8U](https://github.com/jmendeth/v8u).
It's under the 2-clause BSD, feel free to use it in your addons!

<a name="async" />
## Asynchronous versions of the methods

There's discussion on if we should add them. Because Sundown rendering takes such a short time... it's faster to wait one millisecond, than to assume all the time loosed in events and the lot.
<a name="performance" />
## Performance

With the arrival of version 2, we are seeing a **tremendously faster** addon.
Currently, the benchmark (`node benchmark/index --bench`) outputs this:
#### Version 1 (`master` @ 1054ad19010)

```
robotskirt (reuse renderer) completed in 1678ms.
robotskirt (new renderer) completed in 1714ms.
marked completed in 3939ms.
discount completed in 5741ms.
'build' finished successfully (2.383s)
```
#### Version 2.5.2 (`unstable` @ 1df09895262)

```
[1] robotskirt (reuse all) completed in 1354ms.
[2] robotskirt (convenience, reuse all) completed in 1353ms.
[3] robotskirt (new renderer and parser) completed in 3816ms.
[4] robotskirt (convenience, new parser) completed in 1534ms.
'build' finished successfully (2.312s)
```

Tests were run with Node `v0.8.8` (currently the latest stable release)
on a Lenovo Thinkpad T400 (Intel Centrino 2).

As you can see, reusing everything gives **1350** vs. **1678** milliseconds. (+25%)
On the other hand, a single render (including the time to construct the renderer and parser)
now takes **3.8ms** average. (1.7ms before: 2.24x slower)

### CODE REVIEW

**Comment by mildsunrise** [comment]
@benmills I've updated `package.json` to include a homepage, see 4a71d540a8a8.
I have set it to http://benmills.org/robotskirt, which is the repo's home page.
Feel free to change it!

**Comment by benmills** [comment]
It's awesome to see this finally get published. Thanks for the amazing amount of work you put into this @jmendeth

**Comment by mildsunrise** [comment]
Hey, Robotskirt has finally a README! 049e4a0b
[Check it out](https://github.com/benmills/robotskirt/tree/unstable#readme) at the `unstable` branch.

Too short? Too long? More code? Do I deserve a beer?
Feel free to post any reactions / suggestions / objections here,
before it's published. :)

**Comment by mildsunrise** [comment]
[Houdini](https://github.com/vmg/houdini), the escapist (which is partially bundled and used by Sundown to escape HTML)
is now fully exposed! So, you can now [un]escape things with the same speed as Sundown renders markdown.

Turns out that the latest version of Houdini is a bit newer than the version Sundown uses,
but I updated it anyway because the changes are trivial.

Houdini also includes a newer `buffer.h` and `buffer.c`. The internal implementation has changed substantially,
but the API has not, so I'm also updating it.

You can acess features through the `houdini` submodule:

``` javascript
var houdini = require('robotskirt').houdini;
houdini.escapeHTML('<my cr"&azy;HTḿ>l');
```

As always **Robotskirt takes care of the encoding**.
The full list of Houdini functions will be made available in the docs.

PD: After the update, **Robotskirt is a bit faster.** I've updated the benchmark results.

**Comment by benmills** [comment]
Pretty awesome. Big +1 on the updated README.

**Comment by mildsunrise** [comment]
The **convenience** method is now up and fully documented in the (yet to be published) [README](https://github.com/benmills/robotskirt/tree/unstable#the-convenience-way).

**Comment by zzen** [comment]
@jmendeth unfortunately, ever since merging the 2.x code my builds fails since `robotskirt` fails to compile:

```
jakub-air:test jakub$ gcc --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
jakub-air:test jakub$ node --version && npm --version
v0.8.7
1.1.49
jakub-air:test jakub$ npm install robotskirt
npm http GET https://registry.npmjs.org/robotskirt
npm http 304 https://registry.npmjs.org/robotskirt

> robotskirt@2.4.0 install /Users/jakub/Desktop/test/node_modules/robotskirt
> node-waf clean ; node-waf configure build

Nothing to clean (project not configured)
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /Users/jakub/.nvm/v0.8.7 
'configure' finished successfully (0.083s)
Waf: Entering directory `/Users/jakub/Desktop/test/node_modules/robotskirt/build'
[ 1/11] cc: src/markdown.c -> build/Release/src/markdown_1.o
[ 2/11] cc: src/stack.c -> build/Release/src/stack_1.o
[ 3/11] cc: src/buffer.c -> build/Release/src/buffer_1.o
[ 4/11] cc: src/html.c -> build/Release/src/html_1.o
[ 5/11] cc: src/autolink.c -> build/Release/src/autolink_1.o
[ 6/11] cc: src/houdini_href_e.c -> build/Release/src/houdini_href_e_1.o
[ 7/11] cc: src/houdini_html_e.c -> build/Release/src/houdini_html_e_1.o
[ 8/11] cc: src/html_smartypants.c -> build/Release/src/html_smartypants_1.o
[ 9/11] cxx: src/robotskirt.cc -> build/Release/src/robotskirt_2.o
cc1plus: error: unrecognized command line option "-std=c++0x"
Waf: Leaving directory `/Users/jakub/Desktop/test/node_modules/robotskirt/build'
Build failed:  -> task failed (err #1): 
    {task: cxx robotskirt.cc -> robotskirt_2.o}
npm ERR! robotskirt@2.4.0 install: `node-waf clean ; node-waf configure build`
npm ERR! `sh "-c" "node-waf clean ; node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the robotskirt@2.4.0 install script.
npm ERR! This is most likely a problem with the robotskirt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean ; node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls robotskirt
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.1.0
npm ERR! command "/Users/jakub/.nvm/v0.8.7/bin/node" "/Users/jakub/.nvm/v0.8.7/bin/npm" "install" "robotskirt"
npm ERR! cwd /Users/jakub/Desktop/test
npm ERR! node -v v0.8.7
npm ERR! npm -v 1.1.49
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jakub/Desktop/test/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mildsunrise** [comment]
@zzen Your GCC compiler (if it's being used) is **outdated** (see last link)
and doesn't support **C++0x**. It's the new C++ specification
and just like what happened with CSS3, for now **only latest tools support it**.

It provides a lot of useful classes, like function classes, smart pointers and more.
Robotskirt needs it to build.
**[Read more about C++0x support in GCC here.](http://gcc.gnu.org/projects/cxx0x.html) It says the minimum version needed. I'm fine with 4.6.3.**

**Comment by zzen** [comment]
@jmendeth well… that's a bit of a problem. The latest gcc available for latest OS X is 4.2.1. I just checked our hosting provider (Heroku) and they run 4.4.3.

I understand C++11 is surely sexy and useful - but this is a huge blow to compatibility. Any chance this can be cleaned up or do I need to start looking for another sane Markdown parser?

**Comment by mildsunrise** [comment]
I know it. But understand me, it's sooo difficult to do that without C++0x...
And I'm toooo lazy to reinvent (part of) them, because they aren't precisely trivial.

Anyway, I'm worried about compatibility. Weeell, I _could_ try to do it.
In fact, I only need C++0x for `unique_ptr` or `scoped_ptr`.

PD: C++0x doesn't mean **insane**. **Google** recommends its use.

**Comment by zzen** [comment]
@jmendeth I never said C++0x was **insane**. I'm sure it's great and many great companies advocate for it.

All I'm saying is there is now **no way** I can get `robotskirt` to work. It's impossible for me to obtain a working compiler for my OS (it doesn't exist) - and even more importantly, there is **no way I can force Heroku** to use a newer GCC. I would expect that majority of `robotskirt` users & node.js hosting providers will have the same problem.

Likely with time (months? years?) this problem will go away - however in the mean time, it simply means I have to start looking for another parser. :(

**Comment by mildsunrise** [comment]
Checkout now. `v2.5.1` Either install by GIT or NPM.
No longer depends on C++0x. f993fff
Which I really wanted, but, you know, it means more work...

And I had to push my precious README for you.
See what you have done?! :D

PD: Just looking, 4.4 _worked_. It had what Robotskirt needed. It doesn't matter now.

**Comment by zzen** [comment]
@jmendeth build still fails, luckily not on C++0x anymore:

```
...
[12/17] cc: src/html_smartypants.c -> build/Release/src/html_smartypants_1.o
[13/17] cc: src/markdown.c -> build/Release/src/markdown_1.o
[14/17] cc: src/stack.c -> build/Release/src/stack_1.o
[15/17] cxx: src/robotskirt.cc -> build/Release/src/robotskirt_2.o
../src/robotskirt.cc: In function ‘void robotskirt::houdini::init(v8::Handle<v8::Object>)’:
../src/robotskirt.cc:1043: error: ‘SetMethod’ was not declared in this scope
Waf: Leaving directory `/Users/jakub/Documents/apiary/node_modules/robotskirt/build'
Build failed:  -> task failed (err #1): 
    {task: cxx robotskirt.cc -> robotskirt_2.o}
```

**Comment by mildsunrise** [comment]
That's probably because your version of Node doesn't yet have `SetMethod`. Sorry.
I've resolved that (see 030b48e63), but please clone the `unstable` branch and test yourself, before publishing.

PD: Next time I will request more feedback to avoid this. I promise.

**Comment by zzen** [comment]
@jmendeth I can confirm finally compile `robotskirt` unstable branch. Thanks!

I got `Cannot read property 'EXT_FENCED_CODE' of undefined` when trying to read from `flags` property of `HtmlRenderer` instance - but that's probably changed API between v1 and v2 and I'll look that up.

Thanks again.

**Comment by mildsunrise** [comment]
Glad to hear that. I just published it to NPM as v2.5.2.

About the `EXT_FENCED_CODE`, what do you mean?

**Comment by zzen** [comment]
_Sigh_. So I sincerely hope this was done and dusted. It compiles OK on my machine (OS X 10.8). Still doesn't compile well on Heroku though!

```
[15/17] cxx: src/robotskirt.cc -> build/Release/src/robotskirt_2.o
../src/robotskirt.cc: In member function ‘void robotskirt::RendererWrap::makeRenderer(sd_callbacks*, robotskirt::RendererData*)’:
../src/robotskirt.cc:588:34: error: ‘memset’ was not declared in this scope
npm http GET https://registry.npmjs.org/buster-core
Waf: Leaving directory `/home/ubuntu/apiary/node_modules/robotskirt/build'
Build failed:  -> task failed (err #1): 
    {task: cxx robotskirt.cc -> robotskirt_2.o}

~ $ uname -a
Linux b8f85f99-8204-4886-bbbe-257ef9d41016 2.6.32-347-ec2 #52-Ubuntu SMP Fri Jul 27 14:38:36 UTC 2012 x86_64 GNU/Linux

~ $ gcc --version
gcc (Ubuntu 4.4.3-4ubuntu5) 4.4.3
Copyright (C) 2009 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by mildsunrise** [comment]
But, but, ... memset() is a standard method!! :(
It is ANSI C.

Wait. This is a common problem, see:
http://stackoverflow.com/questions/2505365/compiler-error-memset-was-not-declared-in-this-scope

I'll fix ASAP.

2012/9/17 Jakub Nešetřil notifications@github.com

**Comment by mildsunrise** [comment]
@zzen OK, sorry for the delay.
It's now fixed in v2.5.4. See 4e29406cb6022b3e485c6b817197c8103d22c4e7.
I've published to NPM, there shouldn't be any problem now, but I'm not sure...

**Comment by mildsunrise** [comment]
Hey, Robotskirt now exposes the Sundown implementation of [**SmartyPants**](http://daringfireball.net/projects/smartypants)!
Starting from `v2.6.0`, see 95083d0.

It's the _first_ Node.JS module to offer that feature.

**Comment by mildsunrise** [comment]
Thanks to @jgoz, Robotskirt now uses the preferred [Node-GYP](https://github.com/TooTallNate/Node-GYP) to build, see #22.
Starting at `v2.7.0`.
